# SPDX-FileCopyrightText: Sven Eckelmann <sven@narfation.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Codecov

on: [push, pull_request]
env:
  CFLAGS: --coverage

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          make -C test clean && make -C test
          cd test && find . -iname "*".gcno -exec gcov -abcfu {} +
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          files: test/*.gcov
