# SPDX-FileCopyrightText: Sven Eckelmann <sven@narfation.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Test Matrix

on: [push, pull_request]

jobs:
  run:
    strategy:
      matrix:
        cxx: [0, 1]
        cflags: ["-O3", "-g3 -fsanitize=undefined -fsanitize=address -fsanitize=leak"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          make -C test clean && make -C test
        env:
          BUILD_CXX: ${{ matrix.cxx }}
          CFLAGS: ${{ matrix.cflags }}
